### ISSUE TITLE
Am I able to use it with Qt5?

### ISSUE THREAD

**Issue by itatriev** [lastfm/liblastfm#32]
I've noticed commits about Qt5 integration, but you didn't mention it in the description. I'm curious about it.

**Comment by itatriev** [comment]
My question is more about correctness of the description, bc I've stumbled upon a package in the AUR -  [liblastfm-qt5-git](https://aur.archlinux.org/packages/liblastfm-qt5-git/).

**Comment by itatriev** [comment]
Also, we had [discussion here](http://forum.qt.io/topic/55121/is-that-possible-to-use-library-from-qt4-in-qt5/8)

**Comment by xhochy** [comment]
Yes, this library is usable with Qt4 and Qt5 (you just need to compile it for each version).

**Comment by itatriev** [comment]
@xhochy, cool, I'm closing issue. Maybe it should be mentioned in the description? Anyway, thanks ;)
